remove dotsetup and add settings of dctl

diff --git a/bin/dinstall b/bin/dinstall
--- a/bin/dinstall
+++ b/bin/dinstall
@@ -1,18 +1,45 @@
 #!/bin/zsh
 
-typeset -g D{ROOT,USER,REPO,AUTHOR,LICENSE}
-: ${DROOT:=~/.files} ${DUSER:=ytet5uy4}
-: ${DREPO:=https://github.com/${DUSER}/dotfiles}
+typeset -g D{USER,AUTHOR,LICENSE}
+: ${DUSER:=ytet5uy4}
 : ${DAUTHOR:=${DUSER}} ${DLICENSE:=MIT}
 
-typeset -grA fg=(
+# dctl
+export D{REPO,ROOT,PATH,TARGET}
+: ${DREPO:=https://github.com/${DUSER}/dotfiles}
+: ${DROOT:=~/.files}
+: ${DPATH:="$DROOT/src"}
+: ${DTARGET:="$DPATH/.{,config/}*"}
+
+# color
+typeset -gA fg=(
+  default   ''
   main      "${DMAINCOLOR:=75}"
   sub       "${DSUBCOLOR:=240}"
+  accent    "${DACCENTCOLOR:=21}"
   success   "${DSUCCESSCOLOR:=32}"
   error     "${DERRORCOLOR:=129}"
-  underline '\e[4;39;49m'
-  reset     '\e[0;39;49m'
 )
+
+typeset -gA bg=(
+  default ''
+)
+
+typeset -gA text=(
+  fg '38'
+  bg '48'
+)
+
+typeset -gA attr=(
+  default   '0'
+  bold      '1'
+  underline '4'
+  reverse   '7'
+)
+
+# others
+typeset -g TEMPDIR="`mktemp -d /tmp/dotfiles-XXXXXX`"
+typeset -g TEMPDIR_DCTL="$TEMPDIR/dctl"
 
 typeset -gA opt
 while (( $# > 0 )); do
@@ -20,8 +47,7 @@ while (( $# > 0 )); do
     -*)
       [[ "$1" =~ 'f' ]] && opt[full]='1'
       [[ "$1" =~ 'y' ]] && opt[yes]='1'
-      [[ "$1" =~ 'p' ]] && opt[plugin]='1'
-      [[ "$1" =~ 'P' ]] && opt[provision]='1'
+      [[ "$1" =~ 'p' ]] && opt[provision]='1'
       shift
       ;;
     *) shift ;;
@@ -29,162 +55,269 @@ while (( $# > 0 )); do
 done
 
 main() {
-  (( $opt[plugin] )) && install_plugin && exit 0
-  print_header
-  install
+  print-info
+
+  # check git command
+  if ! type git >/dev/null 2>&1; then
+    echo '   Please install git or update your path to run git command'
+    exit 1
+  fi
+
+  if (( $opt[yes] )); then
+    install
+  else
+    private comment msg
+    comment='If the file exists, it will be ruthlessly clobbered'
+    msg='Are you sure you want to continue'
+    print-prompt "$msg" 'install' "$comment" '   '
+  fi
 }
 
-print_header() {
+print-info() {
   clear
-  printf  "\n\e[1;38;5;$fg[main];49m"
+  private color="\x1b[$attr[bold];$text[fg];5;$fg[main]m"
+  private reset="\x1b[$attr[default];$text[fg];5;$fg[default]m"
+
+  printf  "\n$color"
   echo    '          __        __   ____ __ __              '
   echo    '     ____/ /____   / /_ / __//_// /___   _____   '
   echo    '    / __  // __ \ / __// /_ / // // _ \ / ___/   '
   echo    '   / /_/ // /_/ // /_ / __// // //  __//__  /    '
   echo    '   \__,_/ \____/ \__//_/  /_//_/ \___//____/     '
-  printf  "$fg[reset]\n"
+  printf  "$reset\n"
 
-  cprint  "           $DREPO   \n" "$fg[sub]"
-  cprintf '   Author: '            "$fg[main]"; printf "$DAUTHOR"
-  cprintf '   License: '           "$fg[main]"; echo   "$DLICENSE"
-  cprintf '   Provisioning: '      "$fg[main]"
-  (( $opt[provision] )) && cprint 'enable' "$fg[main]" || print 'disable'
-  cprintf '   Full Installation: ' "$fg[main]"
-  (( $opt[full] )) && cprint 'enable' "$fg[main]" || print 'disable'
-  cprintf '   Option Assume yes: ' "$fg[main]"
-  (( $opt[yes] )) && cprint 'enable' "$fg[main]" || print 'disable'
+  print-color-bold  "           $DREPO   \n" "$fg[sub]"
+
+  printf-section 'Author' "$DAUTHOR" '   '
+  print-section 'License' "$DLICENSE" '     '
+
+  print-section 'Options' '' '   '
+  if (( $opt[yes] )); then
+    print-section 'Assume yes' "       `print-enable`" '     '
+  else
+    print-section 'Assume yes' "       `print-disable`" '     '
+  fi
+  if (( $opt[provision] )); then
+    print-section 'Provisioning' "     `print-enable`" '     '
+  else
+    print-section 'Provisioning' "     `print-disable`" '     '
+  fi
+  if (( $opt[full] )); then
+    print-section 'Full Installation' "`print-enable`" '     '
+  else
+    print-section 'Full Installation' "`print-disable`" '     '
+  fi
   echo
-
-  ! (( $opt[yes] )) && warning
 }
 
-warning() {
-  echo '   If the file exists, it will be ruthlessly clobbered'
-  printf '   Are you sure you want to continue (yes/no)? '
-  read -q ANSWER; echo "\n"
-  case $ANSWER in
-    'Y' | 'y' ) install ;;
-    * ) exit 0 ;;
+print-prompt() {
+  printf-color-bold "$4? " "$fg[main]"
+  [[ $3 ]] && printf "$3\n$4  "
+  printf "$1? %s " "`print-brackets Y/n`"
+  read -q input
+  printf "\r$4"
+  [[ $3 ]] && printf "  "
+  printf "$1? %s " "`print-brackets Y/n`"
+  case $input in
+    y )
+      print-color 'Yes\n' "$fg[main]"
+      $=2
+      ;;
+    * )
+      print-color 'no\n' "$fg[main]"
+      exit 0
+      ;;
   esac
+}
+
+print-brackets() {
+  if [[ $1 = Y/n ]]; then
+    printf-color-bold '[' "$fg[sub]"
+    printf-color 'Y' "$fg[main]" "$attr[underline]"
+    printf-color '/' "$fg[main]"
+    printf-color 'n' "$fg[main]" "$attr[underline]"
+    printf-color-bold ']' "$fg[sub]"
+  else
+    printf-color-bold '[' "$fg[accent]"
+    printf '%s' "$1"
+    printf-color-bold ']' "$fg[accent]"
+  fi
+}
+
+print-section() {
+  printf '%s' "$3"
+  printf-color-bold "${(r:1:)1}" "$fg[main]"
+  printf-color "${(l:(($#1-1)):)1}" "$fg[main]"
+  printf-color-bold ': ' "$fg[sub]"
+  printf '%s\n' "$2"
+}
+
+printf-section() {
+  printf '%s' "$3"
+  printf-color-bold "${(r:1:)1}" "$fg[main]"
+  printf-color "${(l:(($#1-1)):)1}" "$fg[main]"
+  printf-color-bold ': ' "$fg[sub]"
+  printf '%s' "$2"
 }
 
 install() {
   # Provisioning
   (( $opt[provision] )) && provisioning
 
-  # Download
-  download
+  # Download dctl
+  download dctl
 
-  path=($path $DROOT/bin(N-/))
-
-  # Backup and Deploy
-  dbackup && ddeploy
+  # Source dctl and install dotfiles with dctl
+  . "$TEMPDIR_DCTL/init.zsh" && dctl -i
 
   # Install plugin
-  (( $opt[full] )) && install_plugin
+  if (( $opt[full] )); then
+    print-header 'Install plugin'
+    typeset plugin=('Dein' 'Zplug' 'TPM')
+    print-spinner "Downloading $plugin" 'download plugin' ' '
+    echo
+  fi
 
   # Restart
-  (( $opt[yes] )) && restart || restart_message
+  if [[ $SHELL:t = zsh ]]; then
+    if (( $opt[yes] )); then
+      restart
+    else
+      private msg
+      msg='Do you want to restart shell'
+      print-prompt "$msg" 'restart'
+    fi
+  fi
 }
 
 provisioning() {
-  typeset ANSIBLE_DREPO tempdir
-  ANSIBLE_DREPO='https://github.com/${DUSER}/ansible-dotfiles/tarball/master'
-  tempdir=`mktemp -d /tmp/dotfiles-XXXXXX`
-
-  underline "Provision for installing dotfiles"
-  echo ' Download playbook of ansible for dotfiles'
-  curl -sL $ANSIBLE_DREPO | tar xzC $tempdir --strip=1
-  cprintf '  Repository: ' "$fg[main]"
-  echo "$ANSIBLE_DREPO"
-  cprintf '  Directory: ' "$fg[main]"
-  echo $tempdir
-  lprintf ' Download playbook of ansible for dotfiles' "ansible-playbook $tempdir/site.yml"
+  download playbook
+  print-spinner 'Run an ansible playbook' "ansible-playbook $tempdir/site.yml" ' '
   echo
-}
-
-download() {
-  underline "Download dotfiles"
-  if lprintf ' Checking git command' 'type git'; then
-    cprintf '  Use: ' "$fg[main]"
-    type -a git | tail -n 1 | awk '{print $3}'
-  else
-    echo ' Please install git or update your path to run git command'
-    exit 1
-  fi
-
-  lprintf ' Downloading dotfiles' "git clone --depth 1 $DREPO $DROOT"
-  cprintf '  Repository: ' "$fg[main]"
-  echo "$DREPO"
-  cprintf '  Directory: ' "$fg[main]"
-  echo "$DROOT"
-  echo
-}
-
-restart_message() {
-  printf "Do you want to restart shell (yes/no)? "
-  read -q ANSWER; echo
-  case $ANSWER in
-    "Y" | "y" ) restart ;;
-    * ) exit 0 ;;
-  esac
 }
 
 restart() { clear; exec $SHELL -l; }
 
-install_plugin() {
-  underline "Install plugin"
+download() {
+  if [[ $1 = playbook ]];then
+    private tempdir_playbook repo_playbook
+    repo_playbook="https://github.com/$DUSER/ansible-dotfiles/tarball/master"
+    tempdir_playbook="$TEMPDIR/playbook"
+    mkdir "$tempdir_playbook"
 
-  typeset -ar NAME=('Dein' 'Zplug' 'TPM')
-
-  lprintf " Downloading ${NAME[*]}" 'download_plugin'
-  echo
-}
-
-download_plugin() {
-  typeset -ar REPO=('Shougo/dein.vim' 'zplug/zplug' 'tmux-plugins/tpm')
-  typeset -r GITHUB_URL='https://github.com/'
-  typeset -ar DIR=(
-    "$HOME/.vim/bundle/repos/github.com/Shougo/dein.vim"
-    "$HOME/.zsh/bundle/zplug"
-    "$HOME/.tmux/bundle/tpm"
-  )
-  paste -d ' ' <(printf "%s\n" "${REPO[@]}") <(printf "%s\n" "${DIR[@]}") \
-    | sed -e "s|^|${GITHUB_URL}|g" \
-    | xargs -L 1 -n 2 -P "${#REPO[*]}" git clone >/dev/null 2>&1
+    print-header 'Provision for installing dotfiles'
+    download-playbook() {
+      curl -sL $repo_playbook | tar xzC $tempdir_playbook --strip=1
+    }
+    print-spinner 'Downloading an ansible playbook' 'download-playbook' ' '
+    printf-color-bold '   -> ' "$fg[main]"
+    print-section 'Repository' "$repo_playbook"
+    printf-color-bold '   -> ' "$fg[main]"
+    print-section 'Directory' " $tempdir_playbook"
+  elif [[ $1 = dctl ]];then
+    typeset repo_dctl="https://github.com/$DUSER/dctl"
+    mkdir "$TEMPDIR_DCTL"
+    print-header 'Download dctl'
+    print-spinner 'Downloading dctl' "git clone --depth 1 $repo_dctl $TEMPDIR_DCTL" ' '
+    printf-color-bold '   -> ' "$fg[main]"
+    print-section 'Repository' "$repo_dctl"
+    printf-color-bold '   -> ' "$fg[main]"
+    print-section 'Directory' " $TEMPDIR_DCTL"
+    echo
+  elif [[ $1 = plugin ]];then
+    typeset repo=('Shougo/dein.vim' 'zplug/zplug' 'tmux-plugins/tpm')
+    typeset url='https://github.com/'
+    typeset dir=(
+      "$HOME/.vim/bundle/repos/github.com/Shougo/dein.vim"
+      "$HOME/.zsh/bundle/zplug"
+      "$HOME/.tmux/bundle/tpm"
+    )
+    paste -d ' ' <(echo "${(F)repo}") <(echo "${(F)dir}") \
+      | sed -e "s|^|$url|g" \
+      | xargs -L 1 -n 2 -P "${#repo[*]}" git clone >/dev/null 2>&1
+  fi
 }
 
 print() { printf "$@\n"; }
 
-cprint() { print "%b%b%b" "\e[1;38;5;${2};49m" "$1" "$fg[reset]"; }
+print-color() {
+  typeset string="$1"
+  typeset reset="\e[$attr[default];$text[fg];5;$fg[default];$text[bg];5;$bg[default]m"
 
-cprintf() { printf "%b%b%b" "\e[1;38;5;${2};49m" "$1" "$fg[reset]"; }
-
-underline() { print "%b%b%b" "$fg[underline]" "$1" "$fg[reset]"; }
-
-lprintf() {
-  typeset -r MSG="$1" CMD="${@:2}"
-  ${=CMD} >/dev/null 2>&1 &
-  while :; do
-    jobs %% > /dev/null 2>&1 || break
-    printf "\r%s%b%s${fg[reset]}" "${MSG}" "\e[1;38;5;${fg[main]};49m" ".  "
-    sleep 0.7
-    jobs %% > /dev/null 2>&1 || break
-    printf "\r%s%b%s%s${fg[reset]}" "${MSG}" "\e[1;38;5;${fg[main]};49m" "." ". "
-    sleep 0.7
-    jobs %% > /dev/null 2>&1 || break
-    printf "\r%s%b%s%s${fg[reset]}" "${MSG}" "\e[1;38;5;${fg[main]};49m" ".." "."
-    sleep 0.7
-  done
-  if wait $!; then
-    printf "\r${MSG}..."
-    cprint 'done' "$fg[success]"
-    return 0
+  typeset color
+  if [[ -n $3 ]]; then
+   color="\e[${3};$text[fg];5;${2}m"
   else
-    printf "\r${MSG}..."
-    cprint 'error' "$fg[error]"
-    return 1
+   color="\e[$attr[default];$text[fg];5;${2}m"
   fi
+
+  print "%b%b%b" "$color" "$string" "$reset"
+}
+
+printf-color() {
+  typeset string="$1"
+  typeset reset="\e[$attr[default];$text[fg];5;$fg[default];$text[bg];5;$bg[default]m"
+
+  typeset color
+  if [[ -n $3 ]]; then
+   color="\e[${3};$text[fg];5;${2}m"
+  else
+   color="\e[$attr[default];$text[fg];5;${2}m"
+  fi
+
+  printf "%b%b%b" "$color" "$string" "$reset"
+}
+
+print-color-bold() {
+  print-color "$1" "$2" "$attr[bold]"
+}
+
+printf-color-bold() {
+  printf-color "$1" "$2" "$attr[bold]"
+}
+
+print-header() {
+  printf-color-bold ":: " "$fg[accent]"
+  print "$1"
+}
+
+print-enable() {
+  print-color-bold 'enable' "$fg[main]"
+}
+
+print-disable() {
+  print 'disable'
+}
+
+print-mark() {
+  if [[ $1 = success ]]; then
+    print-color-bold "\u2714" "$fg[success]"
+  elif [[ $1 = error ]]; then
+    print-color-bold "\u2716" "$fg[error]"
+  fi
+}
+
+print-spinner() {
+  private msg="$1" cmd="$2" space="$3"
+  private -a spinner
+  spinner=(⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏)
+
+  ${=cmd} >/dev/null 2>&1 &
+  while :; do
+    for s in $spinner; do
+      printf "\r%s%s %s" "$space" "`print-color-bold "$s" "$fg[main]"`" "$msg"
+      sleep 0.05
+      if ! jobs %% > /dev/null 2>&1; then
+        if wait $!; then
+          printf "\r%s%s %s\n" "$space" "`print-mark success`" "$msg"
+          return 0
+        else
+          printf "\r%s%s %s\n" "$space" "`print-mark error`" "$msg"
+          return 1
+        fi
+      fi
+    done
+  done
 }
 
 main
